# -*- coding: utf-8 -*-
"""CNN Model Example1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGqL5BOcJGTXMXLee9RE51V_2Joi_FRy

Practical eg

libraries
"""

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
import numpy as np
from keras.preprocessing import image

"""Create model structure"""

# Initialize CNN model
cnn_model=Sequential()
# Added a Convolution layer of 32 filters of 3*3 size ,
# input for this layer has size of 64*64 and 3 represent it is RGB image and
# activation function is "Relu"
cnn_model.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))

# Added a max pooling layer having strided size of 2*2
cnn_model.add(MaxPooling2D(pool_size=(2,2)))

# Again Added a Convolution layer of 32 filters of 3*3 size ,
# input for this layer has size of 64*64 and 3 represent it is RGB image and
# activation function is "Relu"
cnn_model.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))

# Now added a flatten layer to get a 1-D vector
cnn_model.add(Flatten())

# At last we added a fully connected layer with "Relu" activation and
# 128 dim of hidden layer (  output shape)
cnn_model.add(Dense(units=128, activation='relu'))

# At last we added a fully connected layer with "Relu" activation and
# 1 dim of hidden layer (  output shape)
cnn_model.add(Dense(units=1, activation='relu'))

# At last we compile our model with best optimizer Adam , accuracy metrics
# and as we have binary classification task so we are giving loss as
# 'binary_crossentropy'
cnn_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

"""**Image** **processing**"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

test_datagen=ImageDataGenerator(rescale=1./255)

"""**Importing dataset**"""

train_date=train_datagen.flow_from_directory('outputs/img',target_size=(64,64),batch_size=32,class_mode='binary')

test_data=test_datagen.flow_from_directory('outputs/testimg',target_size=(64,64),batch_size=32,class_mode='binary')

"""**fit model**"""

cnn_model.fit(train_date,steps_per_epoch=8000,epochs=1,validation_data=test_data,validation_steps=2000)

"""**Test data**

Here we import a fresh image and we do not know whether it is a cat or dog
"""

test_img=image.load_img('outputs/123.jpg',target_size=(64,64))

#Expand size so that we will not get error
test_img=image.img_to_array(test_img)
test_img=np.expand_dims(test_img,axis=0)

result=cnn_model.predict(test_img)